services:
  habana_frameworks:
    container_name: ${DOCKER_CONTAINER}
    image: ${DOCKER_IMAGE_NAME}
    runtime: habana
    env_file:
      - .env
    working_dir: /${WORKING_DIR}
    environment:
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    volumes:
      - ./:/${WORKING_DIR}/
      - ./models/:/root/.cache/huggingface/hub/
    cap_add:
      - sys_nice
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true

volumes:
  .:
  models:
